### ISSUE TITLE
its not working 

### ISSUE THREAD

**Issue by darksider01011** [mamfyou/Digikala_price_bot#1]
i get this error when running 

Traceback (most recent call last):
  File "C:\Users\11\Downloads\Digikala_price_bot-master\Digikala_price_bot-master\scrap.py", line 32, in <module>
    driver = webdriver.Chrome(executable_path=DRIVER_PATH)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'

**Comment by mamfyou** [comment]
Hello Dear _darksider01011_👋
Thanks a bunch for noticing this issue
According to Selenium Documentation, executable_path was removed in selenium 4.10.0
Since when repository was made there was an older version of selenium installed and probably you've installed the newest version, that's possibly the problem
I just updated the code and removed executable path, and also upgraded selenium version in requirements.txt file
hope you can use it now ✨
@darksider01011

**Comment by darksider01011** [comment]
> Hello Dear _darksider01011_👋 Thanks a bunch for noticing this issue According to Selenium Documentation, executable_path was removed in selenium 4.10.0 Since when repository was made there was an older version of selenium installed and probably you've installed the newest version, that's possibly the problem I just updated the code and removed executable path, and also upgraded selenium version in requirements.txt file hope you can use it now ✨ @darksider01011

Thank you very much
